"use client";
/* eslint-disable react-hooks/set-state-in-effect -- successful server saves synchronize local dirty state */
import{useActionState,useEffect,useRef,useState}from"react";import{updateSettings,type SettingsState}from"./actions";
const days=["Pazartesi","Salı","Çarşamba","Perşembe","Cuma","Cumartesi","Pazar"];
type Row=Record<string,unknown>;const initial:SettingsState={message:null};
export function SettingsForm({settings:s,hours}:{settings:Row;hours:Row[]}){const[state,action,pending]=useActionState(updateSettings,initial),[dirty,setDirty]=useState(false),form=useRef<HTMLFormElement>(null);useEffect(()=>{if(state.errors){const k=Object.keys(state.errors)[0];form.current?.querySelector<HTMLElement>(`[name="${k}"]`)?.focus()}if(state.ok)setDirty(false)},[state]);useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty)e.preventDefault()};addEventListener("beforeunload",warn);return()=>removeEventListener("beforeunload",warn)},[dirty]);const v=(k:string)=>String(s[k]??"");return <form ref={form} action={action} onChange={()=>setDirty(true)} className="space-y-6">
 <Section title="Klinik"><Grid><Field n="clinic_name_tr" l="Klinik adı (TR)" v={v("clinic_name_tr")} required e={state.errors}/><Field n="clinic_name_en" l="Klinik adı (EN)" v={v("clinic_name_en")} e={state.errors}/><Field n="authorized_veterinarian" l="Yetkili veteriner / iletişim" v={v("authorized_veterinarian")} e={state.errors}/><Field n="phone" l="Telefon" v={v("phone")} e={state.errors}/><Field n="whatsapp" l="WhatsApp" v={v("whatsapp")} e={state.errors}/><Field n="public_email" l="Genel e-posta" type="email" v={v("public_email")} e={state.errors}/><Field n="website_url" l="Web sitesi (https)" type="url" v={v("website_url")} e={state.errors}/><Field n="map_url" l="Harita adresi (https)" type="url" v={v("map_url")} e={state.errors}/><Field n="address_tr" l="Adres (TR)" v={v("address_tr")} e={state.errors}/><Field n="address_en" l="Adres (EN)" v={v("address_en")} e={state.errors}/><Field n="registration_text" l="Ruhsat / kayıt metni" v={v("registration_text")} e={state.errors}/></Grid></Section>
 <Section title="Çalışma Saatleri"><div className="space-y-3">{days.map((name,i)=>{const h=hours.find(x=>x.weekday===i+1)??{};return <fieldset key={name} className="grid gap-2 rounded border p-3 sm:grid-cols-5"><legend className="px-1 font-medium">{name}</legend><label><input type="checkbox" name={`day_${i+1}_open`} defaultChecked={Boolean(h.is_open)}/> Açık</label><Time n={`day_${i+1}_start`} l="Açılış" v={String(h.opens_at??"").slice(0,5)}/><Time n={`day_${i+1}_end`} l="Kapanış" v={String(h.closes_at??"").slice(0,5)}/><Time n={`day_${i+1}_break_start`} l="Mola başlangıcı" v={String(h.break_starts_at??"").slice(0,5)}/><Time n={`day_${i+1}_break_end`} l="Mola bitişi" v={String(h.break_ends_at??"").slice(0,5)}/>{state.errors?.[`day_${i+1}`]?<p role="alert" className="text-sm text-red-700 sm:col-span-5">{state.errors[`day_${i+1}`]}</p>:null}</fieldset>})}</div></Section>
 <Section title="Randevu"><Grid><Field n="appointment_min_duration" l="Minimum süre (dk)" type="number" v={v("appointment_min_duration")} e={state.errors}/><Field n="appointment_default_duration" l="Varsayılan süre (dk)" type="number" v={v("appointment_default_duration")} e={state.errors}/><Field n="appointment_max_duration" l="Maksimum süre (dk)" type="number" v={v("appointment_max_duration")} e={state.errors}/><Field n="appointment_buffer" l="Randevu arası (dk)" type="number" v={v("appointment_buffer")} e={state.errors}/><label>İlk durum<select name="appointment_default_status" defaultValue={v("appointment_default_status")} className="mt-1 w-full rounded border p-2"><option value="pending">Bekliyor</option><option value="confirmed">Onaylı</option></select></label><input type="hidden" name="conflict_policy" value="reject"/><Check n="allow_past_appointments" l="Geçmiş randevuya izin ver (yüksek etkili)" c={Boolean(s.allow_past_appointments)}/></Grid></Section>
 <Section title="Hatırlatmalar"><Grid><Field n="reminder_days_before" l="Gün önce (virgülle)" v={(s.reminder_days_before as number[]).join(",")} e={state.errors}/><Field n="reminder_send_hour" l="Gönderim saati" type="time" v={v("reminder_send_hour").slice(0,5)} e={state.errors}/><Field n="reminder_max_retry" l="Maksimum deneme" type="number" v={v("reminder_max_retry")} e={state.errors}/><Check n="whatsapp_enabled" l="WhatsApp etkin" c={Boolean(s.whatsapp_enabled)}/><Check n="email_enabled" l="E-posta etkin" c={Boolean(s.email_enabled)}/><Check n="sms_enabled" l="SMS etkin" c={Boolean(s.sms_enabled)}/></Grid><p className="mt-3 text-sm text-[#526a64]">Sağlayıcı kimlik bilgileri burada saklanmaz; yapılandırılmamış kanallar güvenli biçimde hata verir.</p></Section>
 <Section title="Belgeler"><Grid><Field n="pdf_heading" l="PDF başlığı" v={v("pdf_heading")} e={state.errors}/><Field n="logo_media_path" l="Logo medya yolu" v={v("logo_media_path")} e={state.errors}/><Field n="pdf_footer" l="Alt bilgi" v={v("pdf_footer")} e={state.errors}/><Field n="signature_label" l="İmza etiketi" v={v("signature_label")} e={state.errors}/><label>Varsayılan dil<select name="default_locale" defaultValue={v("default_locale")} className="mt-1 w-full rounded border p-2"><option value="tr">Türkçe</option><option value="en">English</option></select></label><Check n="exclude_internal_notes" l="Dahili notları daima hariç tut" c={true}/></Grid></Section>
 <Section title="Sistem"><p>Saat dilimi: <strong>Europe/Istanbul</strong>. Çakışma politikası mevcut veritabanı kısıtlarını korur.</p></Section>
 {state.message?<p role="status" className={state.ok?"text-green-700":"text-red-700"}>{state.message}</p>:null}<div className="sticky bottom-3 flex items-center gap-3 rounded-xl bg-white p-3 shadow"><button disabled={pending} className="rounded bg-[#0d2922] px-5 py-2 text-white disabled:opacity-50">{pending?"Kaydediliyor…":"Ayarları Kaydet"}</button>{dirty?<span className="text-sm text-amber-700">Kaydedilmemiş değişiklikler var.</span>:null}</div></form>}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-2xl bg-white p-5"><h2 className="mb-4 text-xl font-semibold">{title}</h2>{children}</section>}function Grid({children}:{children:React.ReactNode}){return <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{children}</div>}function Field({n,l,v,type="text",required,e}:{n:string;l:string;v:string;type?:string;required?:boolean;e?:Record<string,string>}){const id=`${n}-error`;return <label>{l}<input name={n} type={type} required={required} defaultValue={v} aria-invalid={Boolean(e?.[n])} aria-describedby={e?.[n]?id:undefined} className="mt-1 w-full rounded border p-2"/>{e?.[n]?<span id={id} className="block text-sm text-red-700">{e[n]}</span>:null}</label>}function Time({n,l,v}:{n:string;l:string;v:string}){return <label className="text-sm">{l}<input name={n} type="time" defaultValue={v} className="mt-1 w-full rounded border p-2"/></label>}function Check({n,l,c}:{n:string;l:string;c:boolean}){return <label className="flex items-center gap-2"><input name={n} type="checkbox" defaultChecked={c}/>{l}</label>}
