/* eslint-disable react-hooks/purity -- Request-time server analytics intentionally uses a single current-time boundary. */
import Link from "next/link";
import { MetricGrid } from "@/src/components/admin/analytics/metric-grid";
import { AnalyticsSection } from "@/src/components/admin/analytics/analytics-section";
import { AlertList } from "@/src/components/admin/analytics/alert-list";
import { ActivityTable } from "@/src/components/admin/analytics/activity-table";
import { QuickActions } from "@/src/components/admin/quick-actions";
import { requireStaff } from "@/src/lib/auth/require-staff";
import { createClient } from "@/src/lib/supabase/server";
import { dashboardTimeBounds } from "@/src/lib/admin/analytics/dashboard-time";

const dt = (v:string) => new Intl.DateTimeFormat("tr-TR", { dateStyle:"short", timeStyle:"short", timeZone:"Europe/Istanbul" }).format(new Date(v));
export default async function AdminPage() {
  const session=await requireStaff(),s=await createClient();if(!s)return <p role="alert">Yönetim verileri yüklenemedi.</p>;
  const {start,end,now,soon,oldDraft,last30}=dashboardTimeBounds();
  const [todayAppointments,pending,confirmed,completed,noShow,owners,pets,todayExams,draftExams,vDue,vOver,pDue,pOver,todayReminders,failedReminders,recentDocsCount,upcoming,overdueVaccines,overdueParasites,attentionReminders,recentExams,recentOwners,recentPets,recentDocs,unassigned,oldDrafts,documentFailures,soonPending]=await Promise.all([
    s.from("appointments").select("id",{count:"exact",head:true}).gte("starts_at",start).lt("starts_at",end).neq("status","cancelled"),s.from("appointments").select("id",{count:"exact",head:true}).eq("status","pending"),s.from("appointments").select("id",{count:"exact",head:true}).eq("status","confirmed"),s.from("appointments").select("id",{count:"exact",head:true}).eq("status","completed"),s.from("appointments").select("id",{count:"exact",head:true}).eq("status","no_show"),s.from("owners").select("id",{count:"exact",head:true}).is("archived_at",null),s.from("pets").select("id",{count:"exact",head:true}).is("archived_at",null),s.from("examinations").select("id",{count:"exact",head:true}).gte("created_at",start).lt("created_at",end),s.from("examinations").select("id",{count:"exact",head:true}).eq("status","draft"),s.from("vaccination_records").select("id",{count:"exact",head:true}).is("archived_at",null).gte("next_due_date",now).lte("next_due_date",soon),s.from("vaccination_records").select("id",{count:"exact",head:true}).is("archived_at",null).lt("next_due_date",now).neq("status","cancelled"),s.from("parasite_records").select("id",{count:"exact",head:true}).is("archived_at",null).gte("next_due_date",now).lte("next_due_date",soon),s.from("parasite_records").select("id",{count:"exact",head:true}).is("archived_at",null).lt("next_due_date",now).neq("status","cancelled"),s.from("reminders").select("id",{count:"exact",head:true}).gte("scheduled_for",start).lt("scheduled_for",end).in("status",["pending","ready"]),s.from("reminders").select("id",{count:"exact",head:true}).eq("status","failed"),s.from("generated_documents").select("id",{count:"exact",head:true}).gte("generated_at",last30),
    s.from("appointments").select("id,starts_at,status,service_key,owner_id,pet_id").gte("starts_at",now).neq("status","cancelled").order("starts_at").limit(6),s.from("vaccination_records").select("id,vaccine_name,next_due_date,pet_id").is("archived_at",null).lt("next_due_date",now).neq("status","cancelled").order("next_due_date").limit(5),s.from("parasite_records").select("id,product_name,next_due_date,pet_id").is("archived_at",null).lt("next_due_date",now).neq("status","cancelled").order("next_due_date").limit(5),s.from("reminders").select("id,reminder_type,status,scheduled_for,recipient_name").in("status",["failed","pending"]).order("scheduled_for").limit(6),s.from("examinations").select("id,visit_type,status,created_at,pet_id").order("created_at",{ascending:false}).limit(6),s.from("owners").select("id,full_name,created_at").is("archived_at",null).order("created_at",{ascending:false}).limit(5),s.from("pets").select("id,name,species,created_at").is("archived_at",null).order("created_at",{ascending:false}).limit(5),s.from("generated_documents").select("id,title,status,generated_at").order("generated_at",{ascending:false}).limit(5),s.from("appointments").select("id",{count:"exact",head:true}).is("assigned_user_id",null).gte("starts_at",now).neq("status","cancelled"),s.from("examinations").select("id",{count:"exact",head:true}).eq("status","draft").lt("created_at",oldDraft),s.from("generated_documents").select("id",{count:"exact",head:true}).eq("status","failed"),s.from("appointments").select("id",{count:"exact",head:true}).eq("status","pending").gte("starts_at",now).lte("starts_at",new Date(Date.now()+3*36e5).toISOString())
  ]);
  const petIds=[...new Set([...(upcoming.data??[]).map(x=>x.pet_id),...(overdueVaccines.data??[]).map(x=>x.pet_id),...(overdueParasites.data??[]).map(x=>x.pet_id),...(recentExams.data??[]).map(x=>x.pet_id)])],ownerIds=[...new Set((upcoming.data??[]).map(x=>x.owner_id))],[petNames,ownerNames]=await Promise.all([petIds.length?s.from("pets").select("id,name").in("id",petIds):Promise.resolve({data:[]}),ownerIds.length?s.from("owners").select("id,full_name").in("id",ownerIds):Promise.resolve({data:[]})]),pm=new Map(petNames.data?.map(x=>[x.id,x.name])),om=new Map(ownerNames.data?.map(x=>[x.id,x.full_name]));
  const metrics=[{label:"Bugünkü Randevular",value:todayAppointments.count??0},{label:"Bekleyen Randevular",value:pending.count??0},{label:"Onaylanmış Randevular",value:confirmed.count??0},{label:"Tamamlanan Randevular",value:completed.count??0},{label:"No-show Randevular",value:noShow.count??0},{label:"Aktif Hayvan Sahipleri",value:owners.count??0},{label:"Aktif Hayvanlar",value:pets.count??0},{label:"Bugünkü Muayeneler",value:todayExams.count??0},{label:"Taslak Muayeneler",value:draftExams.count??0},{label:"Yaklaşan Aşılar",value:vDue.count??0},{label:"Geciken Aşılar",value:vOver.count??0},{label:"Yaklaşan Parazit Uygulamaları",value:pDue.count??0},{label:"Geciken Parazit Uygulamaları",value:pOver.count??0},{label:"Bugün Gönderilecek Hatırlatmalar",value:todayReminders.count??0},{label:"Başarısız Hatırlatmalar",value:failedReminders.count??0},{label:"Son 30 Günde Oluşturulan Belgeler",value:recentDocsCount.count??0}];
  return <><div className="flex flex-wrap justify-between gap-3"><div><p className="text-sm font-semibold uppercase tracking-[.18em] text-[#8a6c32]">MeteVet Yönetim Paneli</p><h1 className="mt-2 text-3xl font-semibold">Klinik Operasyon Merkezi</h1><p className="mt-2 text-[#526a64]">Gerçek Supabase verileriyle güncel durum.</p></div><Link href="/admin/analytics" className="self-start rounded border px-4 py-2 font-medium">Analitiği Aç</Link></div><section className="mt-7" aria-labelledby="today"><h2 id="today" className="mb-4 text-xl font-semibold">Bugün ve Genel Durum</h2><MetricGrid items={metrics}/></section>
  <div className="mt-7 grid gap-6 xl:grid-cols-2"><AnalyticsSection title="Yaklaşan Randevular">{upcoming.data?.length?<ActivityTable headers={["Zaman","Hayvan / Sahip","Hizmet","Durum"]} rows={upcoming.data.map(x=>[dt(x.starts_at),`${pm.get(x.pet_id)??"—"} / ${om.get(x.owner_id)??"—"}`,x.service_key,x.status])}/>:<Empty/>}</AnalyticsSection><AnalyticsSection title="Geciken Koruyucu Sağlık">{overdueVaccines.data?.length||overdueParasites.data?.length?<ul className="space-y-2">{overdueVaccines.data?.map(x=><li key={x.id}><Link className="underline" href={`/admin/vaccines/${x.id}`}>Aşı · {pm.get(x.pet_id)??"Hayvan"} · {x.vaccine_name}</Link></li>)}{overdueParasites.data?.map(x=><li key={x.id}><Link className="underline" href={`/admin/parasites/${x.id}`}>Parazit · {pm.get(x.pet_id)??"Hayvan"} · {x.product_name}</Link></li>)}</ul>:<Empty/>}</AnalyticsSection><AnalyticsSection title="Hatırlatma Dikkat Kuyruğu">{attentionReminders.data?.length?<ul className="space-y-2">{attentionReminders.data.map(x=><li key={x.id}><Link className="flex justify-between rounded border p-3" href={`/admin/reminders/${x.id}`}><span>{x.reminder_type} · {x.recipient_name}</span><b>{x.status}</b></Link></li>)}</ul>:<Empty/>}</AnalyticsSection><AnalyticsSection title="Son Muayeneler">{recentExams.data?.length?<ActivityTable headers={["Tarih","Hayvan","Tür","Durum"]} rows={recentExams.data.map(x=>[dt(x.created_at),pm.get(x.pet_id)??"—",x.visit_type,x.status])}/>:<Empty/>}</AnalyticsSection></div>
  <div className="mt-7 grid gap-6 xl:grid-cols-3"><Recent title="Son Hayvan Sahipleri" items={(recentOwners.data??[]).map(x=>({href:`/admin/owners/${x.id}`,label:x.full_name,detail:dt(x.created_at)}))}/><Recent title="Son Hayvanlar" items={(recentPets.data??[]).map(x=>({href:`/admin/pets/${x.id}`,label:x.name,detail:`${x.species} · ${dt(x.created_at)}`}))}/><Recent title="Son Belgeler" items={(recentDocs.data??[]).map(x=>({href:`/admin/documents/${x.id}`,label:x.title,detail:`${x.status} · ${dt(x.generated_at)}`}))}/></div>
  <div className="mt-7 grid gap-6 xl:grid-cols-2"><AnalyticsSection title="Dikkat Gerektirenler"><AlertList items={[{label:"Geciken aşılar",count:vOver.count??0,href:"/admin/vaccines?overdue=1"},{label:"Geciken parazit uygulamaları",count:pOver.count??0,href:"/admin/parasites?overdue=1"},{label:"Başarısız hatırlatmalar",count:failedReminders.count??0,href:"/admin/reminders?status=failed"},{label:"Eski taslak muayeneler",count:oldDrafts.count??0,href:"/admin/examinations?status=draft"},{label:"Atanmamış yaklaşan randevular",count:unassigned.count??0,href:"/admin/appointments"},{label:"Yakında başlayacak bekleyen randevular",count:soonPending.count??0,href:"/admin/appointments?status=pending"},{label:"Belge üretim hataları",count:documentFailures.count??0,href:"/admin/documents"}]}/></AnalyticsSection><AnalyticsSection title="Sistem Sağlığı"><ul className="space-y-3 text-sm"><Health label="Supabase bağlantısı" ok/><Health label="Başarısız hatırlatma yok" ok={(failedReminders.count??0)===0}/><Health label="Belge üretim hatası yok" ok={(documentFailures.count??0)===0}/><Health label="Atanmamış yaklaşan randevu yok" ok={(unassigned.count??0)===0}/><Health label="7 günden eski taslak muayene yok" ok={(oldDrafts.count??0)===0}/></ul></AnalyticsSection></div>
  <AnalyticsSection title="Hızlı İşlemler"><QuickActions role={session.profile.role}/></AnalyticsSection></>;
}
function Empty(){return <p className="text-sm text-[#526a64]">Henüz veri yok.</p>}function Recent({title,items}:{title:string;items:Array<{href:string;label:string;detail:string}>}){return <AnalyticsSection title={title}>{items.length?<ul className="divide-y">{items.map(x=><li key={x.href} className="py-3"><Link href={x.href} className="font-medium underline">{x.label}</Link><p className="text-sm text-[#526a64]">{x.detail}</p></li>)}</ul>:<Empty/>}</AnalyticsSection>}function Health({label,ok}:{label:string;ok:boolean}){return <li className="flex justify-between rounded border p-3"><span>{label}</span><b>{ok?"Normal":"Dikkat"}</b></li>}
