"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { requireStaff } from "@/src/lib/auth/require-staff";
import { canPermanentlyDelete, canWriteClinicalRecords } from "@/src/lib/admin/permissions";
import { appointmentSources, appointmentStatuses, canTransitionStatus, istanbulLocalToIso, serviceLabels } from "@/src/lib/admin/appointments";
import { createClient } from "@/src/lib/supabase/server";
import type { AppointmentSource, AppointmentStatus } from "@/src/types/database";

export type AppointmentFormState = { message: string | null; errors?: Record<string, string> };
const failed = { message: "İşlem tamamlanamadı. Lütfen tekrar deneyin." };
function values(fd: FormData) { return { owner_id: String(fd.get("ownerId") ?? ""), pet_id: String(fd.get("petId") ?? ""), assigned_user_id: String(fd.get("assignedUserId") ?? "") || null, service_key: String(fd.get("serviceKey") ?? ""), date: String(fd.get("date") ?? ""), start: String(fd.get("startTime") ?? ""), end: String(fd.get("endTime") ?? ""), status: String(fd.get("status") ?? "pending") as AppointmentStatus, source: String(fd.get("source") ?? "admin") as AppointmentSource, reason: String(fd.get("reason") ?? "").trim() || null, internal_notes: String(fd.get("internalNotes") ?? "").trim() || null, pastConfirmed: fd.get("pastConfirmed") === "on", adminOverride: fd.get("adminOverride") === "on" }; }
async function validate(fd: FormData, role: "admin" | "veterinarian" | "staff", currentId?: string) {
  const v = values(fd); const errors: Record<string, string> = {}; const starts_at = istanbulLocalToIso(v.date, v.start); const ends_at = istanbulLocalToIso(v.date, v.end);
  if (!v.owner_id) errors.ownerId = "Hayvan sahibi zorunludur."; if (!v.pet_id) errors.petId = "Hayvan zorunludur."; if (!serviceLabels[v.service_key]) errors.serviceKey = "Geçerli bir hizmet seçin."; if (!starts_at) errors.date = "Geçerli tarih ve başlangıç saati girin."; if (!ends_at || (starts_at && ends_at <= starts_at)) errors.endTime = "Bitiş saati başlangıçtan sonra olmalıdır."; if (!appointmentStatuses.includes(v.status)) errors.status = "Geçerli bir durum seçin."; if (!appointmentSources.includes(v.source)) errors.source = "Geçerli bir kaynak seçin."; if (starts_at && new Date(starts_at) < new Date() && !(role === "admin" && v.pastConfirmed)) errors.date = "Geçmiş randevu için yönetici onayı gerekir.";
  const supabase = await createClient(); if (!supabase) return { errors: { form: failed.message }, v, starts_at, ends_at, supabase: null };
  if (v.pet_id && v.owner_id) { const { data: pet } = await supabase.from("pets").select("id").eq("id", v.pet_id).eq("owner_id", v.owner_id).maybeSingle(); if (!pet) errors.petId = "Seçilen hayvan bu hayvan sahibine ait değil."; }
  if (v.assigned_user_id) { const { data: profile } = await supabase.from("profiles").select("id").eq("id", v.assigned_user_id).maybeSingle(); if (!profile) errors.assignedUserId = "Geçerli bir personel seçin."; }
  if (v.assigned_user_id && starts_at && ends_at) { let query = supabase.from("appointments").select("id").eq("assigned_user_id", v.assigned_user_id).neq("status", "cancelled").lt("starts_at", ends_at).gt("ends_at", starts_at); if (currentId) query = query.neq("id", currentId); const { data } = await query.limit(1); if (data?.length) errors.startTime = "Bu personelin seçilen saat aralığında başka bir randevusu var."; }
  return { errors, v, starts_at, ends_at, supabase };
}
export async function createAppointment(_s: AppointmentFormState, fd: FormData): Promise<AppointmentFormState> { const session = await requireStaff(); if (!canWriteClinicalRecords(session.profile.role)) return { message: "Bu işlem için yetkiniz bulunmuyor." }; const x = await validate(fd, session.profile.role); if (Object.keys(x.errors).length || !x.supabase || !x.starts_at || !x.ends_at) return { message: "Lütfen işaretli alanları düzeltin.", errors: x.errors }; if (x.v.status === "cancelled" && session.profile.role !== "admin") return { message: "Randevuyu yalnızca yönetici iptal edebilir." }; const { date, start, end, pastConfirmed, adminOverride, ...record } = x.v; void date; void start; void end; void pastConfirmed; void adminOverride; const { data, error } = await x.supabase.from("appointments").insert({ ...record, starts_at: x.starts_at, ends_at: x.ends_at }).select("id").single(); if (error || !data) return error?.code === "23P01" ? { message: "Seçilen personelin bu saatte başka bir randevusu var." } : failed; await x.supabase.from("audit_logs").insert({ actor_user_id: session.id, action: "appointment_created", entity_type: "appointment", entity_id: data.id, metadata: { status: record.status, source: record.source, assigned_user_id: record.assigned_user_id } }); revalidatePath("/admin/appointments"); revalidatePath("/admin/calendar"); redirect(`/admin/appointments/${data.id}`); }
// @ts-expect-error Heterogeneous audit metadata is intentionally serialized as JSON.
export async function updateAppointment(id: string, _s: AppointmentFormState, fd: FormData): Promise<AppointmentFormState> { const session = await requireStaff(); if (!canWriteClinicalRecords(session.profile.role)) return { message: "Bu işlem için yetkiniz bulunmuyor." }; const x = await validate(fd, session.profile.role, id); if (Object.keys(x.errors).length || !x.supabase || !x.starts_at || !x.ends_at) return { message: "Lütfen işaretli alanları düzeltin.", errors: x.errors }; const { data: old } = await x.supabase.from("appointments").select("*").eq("id", id).single(); if (!old) return failed; if (!canTransitionStatus(old.status, x.v.status, session.profile.role, x.v.adminOverride)) return { message: "Bu durum geçişine izin verilmiyor.", errors: { status: "Geçersiz durum geçişi." } }; const { date, start, end, pastConfirmed, adminOverride, ...record } = x.v; void date; void start; void end; void pastConfirmed; void adminOverride; const { error } = await x.supabase.from("appointments").update({ ...record, starts_at: x.starts_at, ends_at: x.ends_at }).eq("id", id); if (error) return error.code === "23P01" ? { message: "Seçilen personelin bu saatte başka bir randevusu var." } : failed; const changed = Object.keys(record).filter((key) => key !== "internal_notes" && old[key as keyof typeof old] !== record[key as keyof typeof record]); const events = [{ action: "appointment_updated", metadata: { fields: changed, internal_notes_changed: old.internal_notes !== record.internal_notes } }]; if (old.starts_at !== x.starts_at || old.ends_at !== x.ends_at) events.push({ action: "appointment_rescheduled", metadata: { previous_time: [old.starts_at, old.ends_at], new_time: [x.starts_at, x.ends_at] } }); if (old.status !== record.status) events.push({ action: record.status === "cancelled" ? "appointment_cancelled" : "appointment_status_changed", metadata: { previous_status: old.status, new_status: record.status } }); if (old.assigned_user_id !== record.assigned_user_id) events.push({ action: "appointment_assignment_changed", metadata: { previous_assigned_user: old.assigned_user_id, new_assigned_user: record.assigned_user_id } }); await x.supabase.from("audit_logs").insert(events.map((e) => ({ actor_user_id: session.id, action: e.action, entity_type: "appointment", entity_id: id, metadata: e.metadata }))); revalidatePath("/admin/appointments"); revalidatePath(`/admin/appointments/${id}`); revalidatePath("/admin/calendar"); redirect(`/admin/appointments/${id}`); }
export async function deleteAppointment(id: string) { const session = await requireStaff(); if (!canPermanentlyDelete(session.profile.role)) throw new Error("Bu işlem için yetkiniz bulunmuyor."); const supabase = await createClient(); if (!supabase) throw new Error("İşlem tamamlanamadı."); const { error } = await supabase.from("appointments").delete().eq("id", id); if (error) throw new Error("Randevu silinemedi."); await supabase.from("audit_logs").insert({ actor_user_id: session.id, action: "appointment_deleted", entity_type: "appointment", entity_id: id, metadata: { permanent: true } }); revalidatePath("/admin/appointments"); revalidatePath("/admin/calendar"); redirect("/admin/appointments"); }
