"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { requireStaff } from "@/src/lib/auth/require-staff";
import { createClient } from "@/src/lib/supabase/server";
import { canDeleteReminders, canManageReminders } from "@/src/lib/admin/reminders/reminder-permissions";
import { canTransitionReminder } from "@/src/lib/admin/reminders/reminder-status";
import { generateReminderBatch } from "@/src/lib/admin/reminders/generate-reminders";
import type { ReminderChannel, ReminderStatus, ReminderType } from "@/src/types/database";

export type ReminderFormState={message:string|null;errors?:Record<string,string>};
const types=["appointment_upcoming","appointment_same_day","vaccine_due","vaccine_overdue","parasite_due","parasite_overdue","follow_up_due","custom"];
const channels=["whatsapp","sms","email","internal"];
async function save(id:string|null,_state:ReminderFormState,fd:FormData):Promise<ReminderFormState>{
  const session=await requireStaff();if(!canManageReminders(session.profile.role))return{message:"Bu işlem için yetkiniz bulunmuyor."};const s=await createClient();if(!s)return{message:"İşlem tamamlanamadı."};
  const ownerId=String(fd.get("ownerId")??""),petId=String(fd.get("petId")??"")||null,type=String(fd.get("reminderType")??""),channel=String(fd.get("channel")??""),scheduled=String(fd.get("scheduledFor")??""),message=String(fd.get("renderedMessage")??"").trim()||null;
  const errors:Record<string,string>={};if(!types.includes(type))errors.reminderType="Geçerli tür seçin.";if(!channels.includes(channel))errors.channel="Geçerli kanal seçin.";if(!scheduled||Number.isNaN(Date.parse(scheduled)))errors.scheduledFor="Geçerli tarih seçin.";
  const [owner,pet]=await Promise.all([s.from("owners").select("id,full_name,phone,email").eq("id",ownerId).is("archived_at",null).single(),petId?s.from("pets").select("id,owner_id").eq("id",petId).is("archived_at",null).single():Promise.resolve({data:null})]);
  if(!owner.data)errors.ownerId="Geçerli hayvan sahibi seçin.";if(petId&&(!pet.data||pet.data.owner_id!==ownerId))errors.petId="Hayvan bu kişiye ait değil.";if(Object.keys(errors).length)return{message:"Alanları düzeltin.",errors};
  const record={owner_id:ownerId,pet_id:petId,reminder_type:type as ReminderType,channel:channel as ReminderChannel,scheduled_for:new Date(scheduled).toISOString(),recipient_name:owner.data!.full_name,recipient_phone:owner.data!.phone,recipient_email:owner.data!.email,rendered_message:message,created_by:session.id};
  const result=id?await s.from("reminders").update(record).eq("id",id).in("status",["pending","ready","failed"]).select("id,status").single():await s.from("reminders").insert(record).select("id,status").single();if(result.error||!result.data)return{message:"İşlem tamamlanamadı."};
  await s.from("audit_logs").insert({actor_user_id:session.id,action:id?"reminder_updated":"reminder_created",entity_type:"reminder",entity_id:result.data.id,metadata:{reminder_type:type,channel,scheduled_time:record.scheduled_for}});revalidatePath("/admin/reminders");redirect(`/admin/reminders/${result.data.id}`);
}
export async function createReminder(s:ReminderFormState,f:FormData){return save(null,s,f)}export async function updateReminder(id:string,s:ReminderFormState,f:FormData){return save(id,s,f)}
export async function transitionReminder(id:string,next:ReminderStatus,reason?:string){const session=await requireStaff();if(!canManageReminders(session.profile.role))throw new Error("Yetkiniz bulunmuyor.");const s=await createClient();if(!s)throw new Error("İşlem tamamlanamadı.");const{data:old}=await s.from("reminders").select("status,retry_count,reminder_type,channel").eq("id",id).single();if(!old||!canTransitionReminder(old.status,next))throw new Error("Geçersiz durum geçişi.");if(next==="failed"&&!reason?.trim())throw new Error("Başarısızlık nedeni zorunludur.");const now=new Date().toISOString(),patch={status:next,sent_at:next==="sent"?now:null,sent_by:next==="sent"?session.id:null,failed_at:next==="failed"?now:null,failure_reason:next==="failed"?reason!.trim():null,cancelled_at:next==="cancelled"?now:null};const{error}=await s.from("reminders").update(patch).eq("id",id);if(error)throw new Error("Durum güncellenemedi.");const event=next==="ready"?(old.status==="failed"?"reminder_retried":"reminder_marked_ready"):`reminder_${next}`;await s.from("audit_logs").insert({actor_user_id:session.id,action:event,entity_type:"reminder",entity_id:id,metadata:{reminder_type:old.reminder_type,channel:old.channel,previous_status:old.status,new_status:next,retry_count:old.retry_count}});revalidatePath("/admin/reminders");revalidatePath(`/admin/reminders/${id}`);}
export async function retryReminder(id:string){const session=await requireStaff();if(!canManageReminders(session.profile.role))throw new Error("Yetkiniz bulunmuyor.");const s=await createClient();if(!s)throw new Error("İşlem tamamlanamadı.");const{data}=await s.from("reminders").select("retry_count,status,reminder_type,channel").eq("id",id).single();if(!data||data.status!=="failed")throw new Error("Yalnızca başarısız kayıt denenebilir.");await s.from("reminders").update({status:"ready",retry_count:data.retry_count+1,failed_at:null,failure_reason:null}).eq("id",id);await s.from("audit_logs").insert({actor_user_id:session.id,action:"reminder_retried",entity_type:"reminder",entity_id:id,metadata:{reminder_type:data.reminder_type,channel:data.channel,previous_status:"failed",new_status:"ready",retry_count:data.retry_count+1}});revalidatePath(`/admin/reminders/${id}`);}
export async function deleteReminder(id:string){const session=await requireStaff();if(!canDeleteReminders(session.profile.role))throw new Error("Yetkiniz bulunmuyor.");const s=await createClient();if(!s)throw new Error("İşlem tamamlanamadı.");const{data}=await s.from("reminders").select("reminder_type,channel").eq("id",id).single();if(!data)throw new Error("Kayıt bulunamadı.");await s.from("reminders").delete().eq("id",id);await s.from("audit_logs").insert({actor_user_id:session.id,action:"reminder_deleted",entity_type:"reminder",entity_id:id,metadata:{reminder_type:data.reminder_type,channel:data.channel}});revalidatePath("/admin/reminders");redirect("/admin/reminders");}
export async function generateReminders(){const session=await requireStaff();if(!canManageReminders(session.profile.role))throw new Error("Yetkiniz bulunmuyor.");const s=await createClient();if(!s)throw new Error("İşlem tamamlanamadı.");const result=await generateReminderBatch(s,session.id);await s.from("audit_logs").insert({actor_user_id:session.id,action:"reminder_batch_generated",entity_type:"reminder_batch",metadata:{created_count:result.created,considered_count:result.considered}});revalidatePath("/admin/reminders");revalidatePath("/admin");}
export async function markReminderSent(id:string){await transitionReminder(id,"sent")}export async function markReminderReady(id:string){await transitionReminder(id,"ready")}export async function cancelReminder(id:string){await transitionReminder(id,"cancelled")}export async function failReminder(id:string,fd:FormData){await transitionReminder(id,"failed",String(fd.get("reason")??""))}
