"use client";
import { useActionState, useState } from "react";
import type { AppointmentFormState } from "@/app/admin/appointments/actions";
import { OwnerPetFields } from "@/src/components/admin/owner-pet-fields";
import { appointmentSources, appointmentStatuses, serviceLabels, sourceLabels, statusLabels } from "@/src/lib/admin/appointments";
import type { AppointmentSource, AppointmentStatus, UserRole } from "@/src/types/database";
import { RescheduleSummary } from "./reschedule-summary";
type Owner = { id: string; full_name: string; phone: string }; type Pet = { id: string; owner_id: string; name: string }; type Profile = { id: string; full_name: string; role: UserRole };
type Initial = { owner_id: string; pet_id: string; assigned_user_id: string | null; service_key: string; date: string; start: string; end: string; status: AppointmentStatus; source: AppointmentSource; reason: string | null; internal_notes: string | null };
const empty: AppointmentFormState = { message: null }; const input = "mt-2 min-h-11 w-full rounded-lg border border-[#0d2922]/20 bg-white px-3 py-2 focus:outline-none focus:ring-2 focus:ring-[#cda85f]/50";
export function AppointmentForm({ action, owners, pets, profiles, role, initial, submitLabel }: { action: (s: AppointmentFormState, fd: FormData) => Promise<AppointmentFormState>; owners: Owner[]; pets: Pet[]; profiles: Profile[]; role: UserRole; initial?: Initial; submitLabel: string }) { const [state, formAction, pending] = useActionState(action, empty); const [ownerId, setOwnerId] = useState(initial?.owner_id ?? ""); const [petId, setPetId] = useState(initial?.pet_id ?? ""); const [date, setDate] = useState(initial?.date ?? ""); const [start, setStart] = useState(initial?.start ?? ""); const [end, setEnd] = useState(initial?.end ?? ""); const err = (name: string) => state.errors?.[name]; return <form action={formAction} className="space-y-6" noValidate><div className="grid gap-5 sm:grid-cols-2">
  <OwnerPetFields owners={owners} pets={pets} ownerId={ownerId} petId={petId} onOwnerChange={setOwnerId} onPetChange={setPetId} ownerError={err("ownerId")} petError={err("petId")} canCreatePet={role!=="staff"}/>
  <Field label="Atanan Personel" error={err("assignedUserId")} id="assignedUserId"><select id="assignedUserId" name="assignedUserId" className={input} defaultValue={initial?.assigned_user_id ?? ""}><option value="">Atanmamış</option>{profiles.map((p) => <option key={p.id} value={p.id}>{p.full_name}</option>)}</select></Field>
  <Field label="Hizmet" error={err("serviceKey")} id="serviceKey"><select id="serviceKey" name="serviceKey" className={input} defaultValue={initial?.service_key ?? ""}><option value="">Seçiniz</option>{Object.entries(serviceLabels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></Field>
  <Field label="Tarih" error={err("date")} id="date"><input id="date" name="date" type="date" className={input} value={date} onChange={(e) => setDate(e.target.value)} /></Field><Field label="Başlangıç" error={err("startTime")} id="startTime"><input id="startTime" name="startTime" type="time" className={input} value={start} onChange={(e) => setStart(e.target.value)} /></Field><Field label="Bitiş" error={err("endTime")} id="endTime"><input id="endTime" name="endTime" type="time" className={input} value={end} onChange={(e) => setEnd(e.target.value)} /></Field>
  <Field label="Durum" error={err("status")} id="status"><select id="status" name="status" className={input} defaultValue={initial?.status ?? "pending"}>{appointmentStatuses.map((s) => <option key={s} value={s} disabled={s === "cancelled" && role !== "admin"}>{statusLabels[s]}</option>)}</select></Field><Field label="Kaynak" error={err("source")} id="source"><select id="source" name="source" className={input} defaultValue={initial?.source ?? "admin"}>{appointmentSources.map((s) => <option key={s} value={s}>{sourceLabels[s]}</option>)}</select></Field></div>
  <Field label="Randevu Nedeni" id="reason"><textarea id="reason" name="reason" className={`${input} min-h-24`} defaultValue={initial?.reason ?? ""}/></Field><Field label="Dahili Notlar" id="internalNotes"><textarea id="internalNotes" name="internalNotes" className={`${input} min-h-28`} defaultValue={initial?.internal_notes ?? ""}/></Field>
  <RescheduleSummary original={initial ? { date: initial.date, start: initial.start, end: initial.end } : undefined} current={{ date, start, end }} />{role === "admin" ? <div className="space-y-2"><label className="flex gap-2 text-sm"><input type="checkbox" name="pastConfirmed"/> Geçmiş tarihli randevuyu özellikle onaylıyorum.</label>{initial ? <label className="flex gap-2 text-sm"><input type="checkbox" name="adminOverride"/> Geçersiz durum geçişini yönetici olarak geçersiz kıl.</label> : null}</div> : null}{state.message ? <p aria-live="polite" className="rounded-lg bg-amber-50 p-3 text-sm text-amber-900">{state.message}</p> : null}<button disabled={pending || !petId} className="rounded-lg bg-[#0d2922] px-5 py-3 font-semibold text-white disabled:opacity-60">{pending ? "Kaydediliyor…" : submitLabel}</button></form>; }
function Field({ label, id, error, children }: { label: string; id: string; error?: string; children: React.ReactNode }) { return <div><label htmlFor={id} className="text-sm font-medium">{label}</label>{children}{error ? <p id={`${id}-error`} className="mt-1 text-sm text-red-700">{error}</p> : null}</div>; }
