"use client";

/**
 * Cloudflare Turnstile widget component for the public booking wizard.
 *
 * Renders the Turnstile challenge only when Turnstile is enabled.
 * When disabled, renders nothing — submission proceeds without token.
 *
 * Token lifecycle:
 *   - Generated by Cloudflare after challenge completion
 *   - Passed to server-side verifyTurnstileToken()
 *   - Cleared after: failed submission, expired challenge, successful submission
 *   - NEVER stored, NEVER logged, NEVER in database, NEVER in URL
 *
 * Accessibility:
 *   - Fallback text for screen readers
 *   - aria-live region for status announcements
 */

import { useCallback, useEffect, useRef, useState } from "react";
import { isTurnstileEnabled } from "@/src/lib/public-booking/turnstile-config";

declare global {
  interface Window {
    turnstile?: {
      render: (container: string | HTMLElement, options: TurnstileRenderOptions) => string;
      reset: (widgetId: string) => void;
      getResponse: (widgetId: string) => string | undefined;
      remove: (widgetId: string) => void;
    };
    onTurnstileReady?: () => void;
  }
}

interface TurnstileRenderOptions {
  sitekey: string;
  callback?: (token: string) => void;
  "expired-callback"?: () => void;
  "error-callback"?: () => void;
  theme?: "light" | "dark" | "auto";
  language?: string;
  "refresh-expired"?: "manual" | "auto" | "never";
  tabindex?: number;
}

type TurnstileWidgetProps = {
  locale: "tr" | "en";
  onTokenChange: (token: string | null) => void;
  onError?: (error: string) => void;
};

export function TurnstileWidget({ locale, onTokenChange, onError }: TurnstileWidgetProps) {
  const enabled = isTurnstileEnabled();
  const containerRef = useRef<HTMLDivElement>(null);
  const widgetIdRef = useRef<string | null>(null);
  // Check if script is already loaded (initial check)
  const [scriptLoaded, setScriptLoaded] = useState(() => {
    if (typeof document === "undefined") return false;
    return !!document.getElementById("cf-turnstile-script");
  });
  const [loadError, setLoadError] = useState<string | null>(null);

  // Site key must be available if enabled
  const siteKey = typeof process !== "undefined"
    ? process.env.NEXT_PUBLIC_TURNSTILE_SITE_KEY
    : undefined;

  // Load Turnstile script
  useEffect(() => {
    if (!enabled) return;
    if (scriptLoaded) return;

    const script = document.createElement("script");
    script.id = "cf-turnstile-script";
    script.src = "https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit";
    script.async = true;
    script.defer = true;

    script.onload = () => {
      setScriptLoaded(true);
    };
    script.onerror = () => {
      const msg = locale === "tr"
        ? "Güvenlik doğrulaması yüklenemedi. Lütfen sayfayı yenileyin."
        : "Security verification failed to load. Please refresh the page.";
      setLoadError(msg);
      onError?.(msg);
    };

    document.head.appendChild(script);
  }, [enabled, scriptLoaded, locale, onError]);

  // Render/explicit render Turnstile widget
  useEffect(() => {
    if (!enabled || !scriptLoaded || !containerRef.current || !siteKey) return;

    const renderWidget = () => {
      if (!window.turnstile || !containerRef.current) return;

      // Clean up existing widget
      if (widgetIdRef.current) {
        window.turnstile.remove(widgetIdRef.current);
        widgetIdRef.current = null;
      }

      try {
        const id = window.turnstile.render(containerRef.current, {
          sitekey: siteKey,
          theme: "light",
          language: locale === "tr" ? "tr" : "en",
          "refresh-expired": "manual",
          callback: (token: string) => {
            onTokenChange(token);
          },
          "expired-callback": () => {
            onTokenChange(null);
          },
          "error-callback": () => {
            const msg = locale === "tr"
              ? "Güvenlik doğrulaması başarısız. Lütfen tekrar deneyin."
              : "Security verification failed. Please try again.";
            onError?.(msg);
            onTokenChange(null);
          },
        });
        widgetIdRef.current = id;
      } catch {
        const msg = locale === "tr"
          ? "Güvenlik doğrulaması yüklenemedi."
          : "Security verification failed to load.";
        setLoadError(msg);
        onError?.(msg);
      }
    };

    // window.turnstile may be available immediately or after a tick
    if (window.turnstile) {
      renderWidget();
    } else {
      // Wait for the global callback
      const checkInterval = setInterval(() => {
        if (window.turnstile) {
          clearInterval(checkInterval);
          renderWidget();
        }
      }, 50);

      // Timeout after 10 seconds
      const timeout = setTimeout(() => {
        clearInterval(checkInterval);
        const msg = locale === "tr"
          ? "Güvenlik doğrulaması zaman aşımına uğradı."
          : "Security verification timed out.";
        setLoadError(msg);
        onError?.(msg);
      }, 10000);

      return () => {
        clearInterval(checkInterval);
        clearTimeout(timeout);
      };
    }
  }, [enabled, scriptLoaded, siteKey, locale, onTokenChange, onError]);

  // Cleanup on unmount
  useEffect(() => {
    return () => {
      if (widgetIdRef.current && window.turnstile) {
        try {
          window.turnstile.remove(widgetIdRef.current);
        } catch {
          // Already removed
        }
        widgetIdRef.current = null;
      }
    };
  }, []);

  // Reset function exposed via ref pattern — called by parent
  const resetWidget = useCallback(() => {
    if (widgetIdRef.current && window.turnstile) {
      window.turnstile.reset(widgetIdRef.current);
      onTokenChange(null);
    }
  }, [onTokenChange]);

  // Expose reset via parent ref
  useEffect(() => {
    const container = containerRef.current;
    if (container) {
      (container as HTMLElement & { resetTurnstile?: () => void }).resetTurnstile = resetWidget;
    }
  }, [resetWidget]);

  if (!enabled) {
    return null;
  }

  if (!siteKey && enabled) {
    return (
      <div
        role="alert"
        className="rounded-xl border-2 border-red-300 bg-red-50 p-4 text-sm text-red-700"
      >
        {locale === "tr"
          ? "Güvenlik doğrulaması yapılandırılmamış. Lütfen yöneticinize başvurun."
          : "Security verification is not configured. Please contact your administrator."}
      </div>
    );
  }

  return (
    <div className="my-4">
      <div
        ref={containerRef}
        aria-label={locale === "tr" ? "Güvenlik doğrulaması" : "Security verification"}
        role="region"
      />
      {loadError && (
        <p className="mt-2 text-sm text-red-700" role="alert">
          {loadError}
        </p>
      )}
      <p className="sr-only" aria-live="polite">
        {locale === "tr"
          ? "Güvenlik doğrulaması alanı"
          : "Security verification field"}
      </p>
    </div>
  );
}
