"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { canPermanentlyDelete } from "@/src/lib/admin/permissions";
import { istanbulDateTimeLocalToIso } from "@/src/lib/admin/appointments";
import { canWritePreventive, preventiveStatuses } from "@/src/lib/admin/preventive-care";
import { requireStaff } from "@/src/lib/auth/require-staff";
import { createServerActionClient } from "@/src/lib/supabase/server-action";

export type VaccineState={message:string|null;errors?:Record<string,string>};
const value=(fd:FormData)=>({ownerId:String(fd.get("ownerId")??""),petId:String(fd.get("petId")??""),veterinarianId:String(fd.get("veterinarianId")??""),appointmentId:String(fd.get("appointmentId")??"")||null,vaccineName:String(fd.get("vaccineName")??"").trim(),manufacturer:String(fd.get("manufacturer")??"").trim(),batchNumber:String(fd.get("batchNumber")??"").trim(),serialNumber:String(fd.get("serialNumber")??"").trim()||null,doseNumber:Number(fd.get("doseNumber")),route:String(fd.get("route")??"").trim(),administrationDate:String(fd.get("administrationDate")??""),nextDueDate:String(fd.get("nextDueDate")??"")||null,status:String(fd.get("status")??"completed"),certificateNumber:String(fd.get("certificateNumber")??"").trim()||null,notes:String(fd.get("notes")??"").trim()||null,internalNotes:String(fd.get("internalNotes")??"").trim()||null});

async function save(id:string|null,_state:VaccineState,fd:FormData):Promise<VaccineState>{
  const session=await requireStaff(); if(!canWritePreventive(session.profile.role))return{message:"Yetkiniz bulunmuyor."};
  const v=value(fd),errors:Record<string,string>={};
  const administrationIso=istanbulDateTimeLocalToIso(v.administrationDate),nextDueIso=v.nextDueDate?istanbulDateTimeLocalToIso(v.nextDueDate):null;if(!v.ownerId)errors.ownerId="Hayvan sahibi zorunludur.";if(!v.petId)errors.petId="Hayvan zorunludur.";if(!v.veterinarianId)errors.veterinarianId="Veteriner hekim zorunludur.";if(!v.vaccineName)errors.vaccineName="Aşı adı zorunludur.";if(!v.manufacturer)errors.manufacturer="Üretici zorunludur.";if(!v.batchNumber)errors.batchNumber="Parti numarası zorunludur.";if(!v.route)errors.route="Uygulama yolu zorunludur.";if(!administrationIso)errors.administrationDate="Geçerli uygulama tarihi zorunludur.";if(v.nextDueDate&&!nextDueIso)errors.nextDueDate="Geçerli sonraki doz tarihi girin.";if(!Number.isInteger(v.doseNumber)||v.doseNumber<=0)errors.doseNumber="Doz pozitif tam sayı olmalıdır.";if(!preventiveStatuses.includes(v.status as never))errors.status="Geçerli durum seçin.";
  const s=await createServerActionClient();if(!s)return{message:"İşlem tamamlanamadı."};
  const[{data:owner},{data:pet},{data:vet}]=await Promise.all([s.from("owners").select("id").eq("id",v.ownerId).is("archived_at",null).maybeSingle(),s.from("pets").select("id,owner_id").eq("id",v.petId).eq("owner_id",v.ownerId).is("archived_at",null).maybeSingle(),s.from("profiles").select("id,role").eq("id",v.veterinarianId).eq("role","veterinarian").eq("status","active").maybeSingle()]);
  if(!owner)errors.ownerId="Geçerli aktif bir hayvan sahibi seçin.";if(!pet)errors.petId="Seçilen aktif hayvan bu hayvan sahibine ait değil.";if(!vet)errors.veterinarianId="Geçerli bir veteriner hekim seçin.";
  if(v.appointmentId&&pet){const{data:appointment}=await s.from("appointments").select("id").eq("id",v.appointmentId).eq("owner_id",v.ownerId).eq("pet_id",v.petId).maybeSingle();if(!appointment)errors.appointmentId="Randevu seçilen sahip ve hayvanla eşleşmiyor.";}
  if(Object.keys(errors).length)return{message:"Alanları düzeltin.",errors};
  const record={pet_id:v.petId,owner_id:v.ownerId,veterinarian_id:v.veterinarianId,appointment_id:v.appointmentId,vaccine_name:v.vaccineName,manufacturer:v.manufacturer,batch_number:v.batchNumber,serial_number:v.serialNumber,dose_number:v.doseNumber,route:v.route,administration_date:administrationIso!,next_due_date:nextDueIso,status:v.status as"scheduled"|"completed"|"expired"|"cancelled",certificate_number:v.certificateNumber,notes:v.notes,internal_notes:v.internalNotes};
  const result=id?await s.from("vaccination_records").update(record).eq("id",id).select("id").single():await s.from("vaccination_records").insert(record).select("id").single();if(result.error||!result.data)return{message:"İşlem tamamlanamadı."};
  await s.from("audit_logs").insert({actor_user_id:session.id,action:id?"vaccine_updated":record.status==="completed"?"vaccine_completed":"vaccine_created",entity_type:"vaccination_record",entity_id:result.data.id,metadata:{fields:id?["preventive_record"]:[],status:record.status}});revalidatePath("/admin/vaccines");revalidatePath(`/admin/pets/${v.petId}`);redirect(`/admin/vaccines/${result.data.id}`);
}
export async function createVaccine(s:VaccineState,f:FormData){return save(null,s,f)}export async function updateVaccine(id:string,s:VaccineState,f:FormData){return save(id,s,f)}
async function life(id:string,action:"archive"|"restore"|"delete"){const session=await requireStaff();if(!canPermanentlyDelete(session.profile.role))throw new Error("Yetkiniz bulunmuyor.");const s=await createServerActionClient();if(!s)throw new Error("İşlem başarısız.");const{data}=await s.from("vaccination_records").select("pet_id").eq("id",id).single();if(!data)throw new Error("Kayıt yok.");const result=action==="delete"?await s.from("vaccination_records").delete().eq("id",id):await s.from("vaccination_records").update({archived_at:action==="archive"?new Date().toISOString():null}).eq("id",id);if(result.error)throw new Error("İşlem başarısız.");await s.from("audit_logs").insert({actor_user_id:session.id,action:`vaccine_${action}d`,entity_type:"vaccination_record",entity_id:id,metadata:{}});revalidatePath("/admin/vaccines");revalidatePath(`/admin/pets/${data.pet_id}`);if(action==="delete")redirect("/admin/vaccines")}
export async function archiveVaccine(id:string){await life(id,"archive")}export async function restoreVaccine(id:string){await life(id,"restore")}export async function deleteVaccine(id:string){await life(id,"delete")}
