create table public.vaccination_records (
 id uuid primary key default gen_random_uuid(), pet_id uuid not null references public.pets(id) on delete restrict,
 owner_id uuid not null references public.owners(id) on delete restrict, veterinarian_id uuid references public.profiles(id) on delete set null,
 appointment_id uuid references public.appointments(id) on delete set null, vaccine_name text not null, manufacturer text not null,
 batch_number text not null, serial_number text, dose_number integer not null check(dose_number>0), route text not null,
 administration_date timestamptz not null, next_due_date timestamptz, status text not null check(status in('scheduled','completed','expired','cancelled')),
 certificate_number text, notes text, internal_notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), archived_at timestamptz
);
create table public.parasite_records (
 id uuid primary key default gen_random_uuid(), pet_id uuid not null references public.pets(id) on delete restrict,
 owner_id uuid not null references public.owners(id) on delete restrict, veterinarian_id uuid references public.profiles(id) on delete set null,
 treatment_type text not null check(treatment_type in('internal','external','combined')), product_name text not null, batch_number text,
 administration_date timestamptz not null, next_due_date timestamptz, status text not null check(status in('scheduled','completed','expired','cancelled')),
 notes text, internal_notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), archived_at timestamptz
);
create index vaccination_records_pet_id_idx on public.vaccination_records(pet_id);create index vaccination_records_owner_id_idx on public.vaccination_records(owner_id);create index vaccination_records_status_idx on public.vaccination_records(status);create index vaccination_records_administration_date_idx on public.vaccination_records(administration_date desc);create index vaccination_records_next_due_date_idx on public.vaccination_records(next_due_date);
create index parasite_records_pet_id_idx on public.parasite_records(pet_id);create index parasite_records_owner_id_idx on public.parasite_records(owner_id);create index parasite_records_status_idx on public.parasite_records(status);create index parasite_records_administration_date_idx on public.parasite_records(administration_date desc);create index parasite_records_next_due_date_idx on public.parasite_records(next_due_date);
create trigger vaccination_records_set_updated_at before update on public.vaccination_records for each row execute function public.set_updated_at();create trigger parasite_records_set_updated_at before update on public.parasite_records for each row execute function public.set_updated_at();
create function public.protect_preventive_record() returns trigger language plpgsql set search_path='' as $$ declare expected_owner uuid; begin select owner_id into expected_owner from public.pets where id=new.pet_id;if expected_owner is null or expected_owner<>new.owner_id then raise exception 'Owner and pet do not match.' using errcode='23514';end if;if ((tg_op='INSERT' and new.archived_at is not null) or (tg_op='UPDATE' and new.archived_at is distinct from old.archived_at)) and (select auth.role())='authenticated' and not(select public.is_admin()) then raise exception 'Only administrators can manage archives.' using errcode='42501';end if;return new;end;$$;
create trigger vaccination_records_protect before insert or update on public.vaccination_records for each row execute function public.protect_preventive_record();create trigger parasite_records_protect before insert or update on public.parasite_records for each row execute function public.protect_preventive_record();
alter table public.vaccination_records enable row level security;alter table public.parasite_records enable row level security;
create policy "Staff read vaccinations" on public.vaccination_records for select to authenticated using((select public.is_staff()));create policy "Clinical staff insert vaccinations" on public.vaccination_records for insert to authenticated with check((select public.is_clinical_staff()));create policy "Clinical staff update vaccinations" on public.vaccination_records for update to authenticated using((select public.is_clinical_staff())) with check((select public.is_clinical_staff()));create policy "Admins delete vaccinations" on public.vaccination_records for delete to authenticated using((select public.is_admin()));
create policy "Staff read parasite records" on public.parasite_records for select to authenticated using((select public.is_staff()));create policy "Clinical staff insert parasite records" on public.parasite_records for insert to authenticated with check((select public.is_clinical_staff()));create policy "Clinical staff update parasite records" on public.parasite_records for update to authenticated using((select public.is_clinical_staff())) with check((select public.is_clinical_staff()));create policy "Admins delete parasite records" on public.parasite_records for delete to authenticated using((select public.is_admin()));
revoke all on public.vaccination_records,public.parasite_records from anon;grant select,insert,update,delete on public.vaccination_records,public.parasite_records to authenticated;
