export const SETTING_KEYS = ["clinic_name_tr","clinic_name_en","authorized_veterinarian","phone","whatsapp","public_email","address_tr","address_en","map_url","website_url","registration_text","appointment_default_duration","appointment_min_duration","appointment_max_duration","appointment_buffer","appointment_default_status","allow_past_appointments","conflict_policy","reminder_days_before","reminder_send_hour","reminder_max_retry","whatsapp_enabled","email_enabled","sms_enabled","pdf_heading","logo_media_path","pdf_footer","signature_label","default_locale","exclude_internal_notes"] as const;
export type SettingKey=(typeof SETTING_KEYS)[number];
const secret=/(password|token|secret|service.?role|api.?key|credential)/i;
export function normalizePhone(value:string){const x=value.replace(/[^+\d]/g,"");if(!x)return null;return /^\+[1-9]\d{7,14}$/.test(x)?x:undefined}
export function safeUrl(value:string){if(!value)return null;try{const u=new URL(value);return u.protocol==="https:"&&value.length<=500?value:undefined}catch{return undefined}}
export function validateSettingsInput(fd:FormData){const errors:Record<string,string>={},input:Record<string,string|boolean|number|number[]|null>={};for(const key of fd.keys())if(!SETTING_KEYS.includes(key as SettingKey)&&!key.startsWith("$ACTION_")&&!/^day_[1-7]_(open|start|end|break_start|break_end)$/.test(key))errors.form="Geçersiz ayar alanı gönderildi.";for(const key of SETTING_KEYS){if(secret.test(key)){errors.form="Gizli bilgi ayarlarda saklanamaz.";continue}const raw=String(fd.get(key)??"").trim();input[key]=raw||null}
  const required=(k:SettingKey,min:number,max:number)=>{const v=String(input[k]??"");if(v.length<min||v.length>max)errors[k]="Geçersiz uzunluk."};required("clinic_name_tr",2,120);
  for(const k of ["phone","whatsapp"] as const){const v=normalizePhone(String(input[k]??""));if(v===undefined)errors[k]="Telefonu ülke koduyla girin (örn. +90…).";else input[k]=v}
  const email=String(input.public_email??"");if(email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))errors.public_email="Geçerli bir e-posta girin.";
  for(const k of ["map_url","website_url"] as const){const v=safeUrl(String(input[k]??""));if(v===undefined)errors[k]="Yalnızca güvenli https adresi girin.";else input[k]=v}
  for(const k of ["appointment_default_duration","appointment_min_duration","appointment_max_duration","appointment_buffer","reminder_max_retry"] as const)input[k]=Number(input[k]);
  const min=Number(input.appointment_min_duration),def=Number(input.appointment_default_duration),max=Number(input.appointment_max_duration),buffer=Number(input.appointment_buffer);if(!(min>=5&&min<=def&&def<=max&&max<=480&&buffer>=0&&buffer<=120))errors.appointment_default_duration="Süreler 5–480 dakika arasında ve min ≤ varsayılan ≤ max olmalıdır.";
  input.reminder_days_before=String(input.reminder_days_before??"").split(",").map(Number).filter(Number.isInteger);if(!(input.reminder_days_before as number[]).length||(input.reminder_days_before as number[]).some(x=>x<0||x>365))errors.reminder_days_before="0–365 arasında, virgülle ayrılmış günler girin.";
  for(const k of ["allow_past_appointments","whatsapp_enabled","email_enabled","sms_enabled","exclude_internal_notes"] as const)input[k]=fd.get(k)==="on";
  input.conflict_policy="reject";return{input:input as never,errors};}
export function validateHours(open:boolean,start:string,end:string,breakStart:string,breakEnd:string){if(!open)return start||end||breakStart||breakEnd?"Kapalı günlerde saat bırakmayın.":null;if(!start||!end||start>=end)return"Açılış saati kapanıştan önce olmalıdır.";if(Boolean(breakStart)!==Boolean(breakEnd)||breakStart&&!(start<breakStart&&breakStart<breakEnd&&breakEnd<end))return"Mola çalışma aralığının içinde olmalıdır.";return null}
